id = "boolean-toggle"
name = "Boolean Toggle"
version = "0.1.2"
schema_version = 1
authors = ["Your Name"]
description = "Toggle true/false, yes/no, on/off, 1/0"

[language_servers.boolean-toggle]
name = "Boolean Toggle LSP"
languages = [
    "Markdown", "Plain Text", "Rust", "JavaScript", "TypeScript",
    "Python", "C", "C++", "Go", "Java", "Ruby", "PHP", "HTML", "CSS", "JSON",
    "TOML", "YAML"
]
