name: Continuous Integration
on:
  - push
  - pull_request

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: boolean-toggle-lsp-x86_64-unknown-linux-gnu
          # Linux Aarch64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            asset_name: boolean-toggle-lsp-aarch64-unknown-linux-gnu
          # macOS Intel
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: boolean-toggle-lsp-x86_64-apple-darwin
          # macOS Apple Silicon (M1/M2/M3)
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: boolean-toggle-lsp-aarch64-apple-darwin
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: boolean-toggle-lsp-x86_64-pc-windows-msvc.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Dependencies
        run: cargo fetch

      - name: Build
        # Notice we explicitly point to the server's Cargo.toml
        run: cargo build --release --target ${{ matrix.target }} --manifest-path server/Cargo.toml

      - name: Tests
        run: make test

      # - name: "Publish to Zed Extensions Registry"
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      #   uses: huacnlee/zed-extension-action@v2
      #   with:
      #     extension-name: boolean-toggle
      #     push-to: unlight/extensions # fork of zed-industries/extensions
      #   env:
      #     # Personal access token with "repo" and "workflow" scopes
      #     COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
